apiVersion: apps/v1
kind: Deployment
metadata:
  name: hall
  labels:
    app: hall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hall
  template:
    metadata:
      labels:
        app: hall
    spec:
      containers:
        - name: hall
          image: skccuser23.azurecr.io/hall:v1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5