apiVersion: apps/v1
kind: Deployment
metadata:
  name: workercenter
  labels:
    app: workercenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workercenter
  template:
    metadata:
      labels:
        app: workercenter
    spec:
      containers:
        - name: workercenter
          image: skccuser23.azurecr.io/workercenter:v1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5